# -*- coding: utf-8 -*-
"""deep_learning_constants.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I_sQ8bCmWqKV7ObK6WXm_g3FbWgir-h8
"""

#*******************************************************************************************
 #
 #  File Name:  deep_learning_constants.py
 #
 #  File Description:
 #      This Python script, deep_learning_constants.py, contains generic Python
 #      constants for completing common neural network tasks.
 #
 #
 #  Date            Description                             Programmer
 #  ----------      ------------------------------------    ------------------
 #  12/02/2023      Initial Development                     Nicholas J. George
 #
 #******************************************************************************************/

CONSTANT_LOCAL_FILE_NAME = 'deep_learning_constants.py'

features_integer = 0